### ISSUE TITLE
javaagent explaination

### ISSUE THREAD

**Issue by henningbro** [pjfanning/micrometer-pekko#105]
Hi,
we are trying to make use of this library and have an issue with using the "-javaagent" parameter.
Our issue is, that we have to open up the jar, remove the aspectjweaver.jar from the resulting jar and than add it as a javaagent in our Dockerfile. I spare you the details. But we don't like what we did there.

Firstly we would like to understand, why we actually need it?
Secondly is there any way around using the -javaagent parameter?

Could you add those details to the readme?

Best Regards

**Comment by pjfanning** [comment]
No - this lib entirely relies on the aspectjweaver jar being loaded as javaagent.

**Comment by pjfanning** [comment]
If you are unfamiliar with Aspect Oriented Programming, maybe you can read https://www.baeldung.com/aspectj

**Comment by pjfanning** [comment]
An alternative that doesn't use AOP is https://github.com/erikvanoosten/metrics-scala - but with that lib, you will need to adjust your code to get the metrics to be recorded.
